version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.17.0
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Building Next.js app..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  base-directory: out
  files:
    - '**/*'
